version: "3"
services:
  wordpress:
    build:
      context: requirements/WordPress/
      dockerfile: Dockerfile
    depends_on:
      - mariadb
      - redis
    image: wordpress:latest
    container_name: wordpress
    restart: always
    env_file:
    - ./.env
    volumes:
      - wordpress-sites:/var/www/html/
    networks:
    - inception

  nginx:
    build:
      context: requirements/Nginx/
      dockerfile: Dockerfile
    depends_on:
      - wordpress
    image: nginx:latest
    container_name: Nginx
    restart: always
    env_file:
      - ./.env
    ports:
      - '443:443'
    volumes:
      - wordpress-sites:/var/www/html/
    networks:
      - inception

  mariadb:
    build:
      context: requirements/MariaDB/
      dockerfile: Dockerfile
    image: mariadb:latest
    container_name: Mariadb
    restart: always
    env_file:
    - ./.env
    ports:
      - '3306:3306'
    volumes:
      - data_db:/var/lib/mysql
    networks:
      - inception

  ftp:
    build:
      context: srcs/requirements/Bonus/Ftp
      dockerfile: Dockerfile
    image: ftp:latest
    container_name: ftp
    restart: always
    ports:
      - 21:21
    volumes:
      - wordpress-sites:/wordpress
    networks:
      - inception

  static_site:
    build:
      context: srcs/requirements/Bonus/static_website
      dockerfile: Dockerfile
    image: static:latest
    container_name: static
    restart: always
    ports:
      - 80:80
    networks:
      - inception

  redis:
    build:
      context: requirements/Bonus/redis
      dockerfile: Dockerfile
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - inception
  
  adminer:
    build:
      context: requirements/Bonus/Adminer/
      dockerfile: Dockerfile
    image: adminer:latest
    container_name: Adminer
    restart: always
    networks:
      - inception
  cadvisor:
    build:
      context: requirements/Bonus/cadvisor
      dockerfile: Dockerfile
    image: cadvisor:latest
    container_name: Cadvisor
    ports:
      - 8080:8080
    networks:
      - inception

volumes:
  data_db:
    driver_opts:
      type: none
      o: bind
      device: /Users/mrobaii/data/data_db
  wordpress-sites:  
    driver_opts:
      type: none
      o: bind
      device: /Users/mrobaii/data/wordpress-sites                                                                                                  

networks:
  inception:
    driver: bridge
