version: "3"
services:
  wordpress:
    build:
      context: WordPress/
      dockerfile: Dockerfile
    image: wordpress:latest
    container_name: wordpress
    volumes:
      - wordpress-sites:/mrobaii.42.fr
    ports:
      - '9000:9000'
    networks:
    - inception

  nginx:
    build:
      context: Nginx/
      dockerfile: Dockerfile
    depends_on:
      - wordpress
    image: nginx:latest
    container_name: Nginx
    ports:
      - '443:443'
    volumes:
      - wordpress-sites:/var/www/html/
    networks:
      - inception

  # mariadb:
  #   build:
  #     context: Mariadb/
  #     dockerfile: Dockerfile
  #   image: mariadb:latest
  #   container_name: Mariadb
  #   ports:
  #     - '3306:3306'
  #   volumes:
  #     - data_db:/var/lib/mysql
  #   networks:
  #   - inception

volumes:
  data_db:
  wordpress-sites:                                                                                                    

networks:
  inception:
    driver: bridge